services:
  app:
    build:
      context: .
      dockerfile: docker/DockerFile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - app-network
    restart: always

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 20s

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
